### ISSUE TITLE
Export API: Getting lists with segments returns nothing

### ISSUE THREAD

**Issue by jonasc** [michaelhelmick/python-mailsnake#11]
Hi,

retrieving the members of a list works great via the export api but trying to retrieve just a segment of the list always returns an empty array (not even the header row). Just before trying to get this I try my segmentation with campaignSegmentTest and it returns a value bigger than zero.

This is my code:

``` python
kwargs = {'segment': {'match': 'all', 'conditions': [
    {'field': 'static_segment', 'op': 'eq', 'value': segment_id}
]}}
# This prints a number bigger than zero
print _mailchimp_connection.campaignSegmentTest(
    list_id=self.id, options=kwargs['segment']
)
members = _mailchimp_export_connection.list(
    id=self.id, **kwargs
)
# members == [] now
```

The problem is that it doesn't even throw an error but just returns an empty array. Visting the API url directly ( http://us5.api.mailchimp.com/export/1.0/list/?apikey=MY_API_KEY&id=MY_LIST_ID&segment[match]=all&segment[conditions][0][field]=static_segment&segment[conditions][0][op]=eq&segment[conditions][0][value]=MY_SEGMENT_ID )

The following (just a list) works:

``` python
members = _mailchimp_export_connection.list(id=self.id)
# members contains a nice result
```

**Comment by ravikumarpundr** [comment]
is export api with static_segment working?
