### ISSUE TITLE
setup.py should mention Python 3 support

### ISSUE THREAD

**Issue by giampaolo** [michaelhelmick/python-mailsnake#27]
This is helpful for CLI tools like "caniusepython3". I erroneously thought simplekv didn't have python 3 support because of that. 
Fixing this is easy. In setup.py:

    classifiers=[
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 3',
    ],

**Comment by svisser** [comment]
Please create a new release of the `mailsnake` package that includes this change - it'd be a great help in keeping track of what packages are not yet Python 3 compatible (I thought the same thing before seeing this).

**Comment by michaelhelmick** [comment]
@svisser 1.6.4 is available on pypi

**Comment by svisser** [comment]
@michaelhelmick thank you, much appreciated!
